-- =============================================================================
-- 0005 — Remove the unused tenant_id from rate_limit_counters.
--
-- The column was never written: the tenant is already part of the subject key
-- ("<tenant>:<visitor>"), because the chat endpoint must be able to refuse a
-- request before a tenant context exists, so the table cannot be RLS-scoped.
--
-- Leaving a tenant_id there implied a scoping that did not exist — and the
-- isolation suite, which requires every table carrying tenant_id to have a
-- policy, correctly refused it.
-- =============================================================================
ALTER TABLE rate_limit_counters DROP COLUMN tenant_id;
