/**
 * Embed the migration SQL into a TypeScript module.
 *
 *   npm run migrations:embed
 *
 * `db/migrations/` stays the source of truth and the CLI reads it from disk.
 * A serverless function cannot: its working directory is not the repository,
 * so a path built from `process.cwd()` resolves to nothing and the hosted
 * database can never be migrated at all.
 *
 * So the SQL is compiled in. `tests/schema/embedded-migrations.test.ts` asserts
 * the generated module still matches the files byte for byte, which is what
 * stops a deployed database from being a migration behind its code.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SOURCE = 'db/migrations';
const TARGET = 'src/server/db/migrations.generated.ts';

function main() {
  const files = readdirSync(SOURCE).filter((f) => f.endsWith('.sql')).sort();

  const entries = files.map((file) => {
    const sql = readFileSync(join(SOURCE, file), 'utf8');
    return {
      name: file,
      sql,
      checksum: createHash('sha256').update(sql).digest('hex'),
    };
  });

  const body = entries
    .map(
      (entry) =>
        `  {\n    name: ${JSON.stringify(entry.name)},\n` +
        `    checksum: ${JSON.stringify(entry.checksum)},\n` +
        `    sql: ${JSON.stringify(entry.sql)},\n  },`,
    )
    .join('\n');

  writeFileSync(
    TARGET,
    `/**
 * Generated by scripts/embed-migrations.ts. Do not edit.
 *
 * The contents of db/migrations, compiled in so a serverless function can run
 * them — its working directory is not the repository, so reading them from
 * disk is not possible there. Regenerate with \`npm run migrations:embed\`.
 */
export interface EmbeddedMigration {
  name: string;
  checksum: string;
  sql: string;
}

export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = [
${body}
];
`,
  );

  console.log(`Embedded ${entries.length} migrations into ${TARGET}.`);
}

main();
